### ISSUE TITLE
Crashes on push from dev editor

### ISSUE THREAD

**Issue by cbrez101** [MobileChromeApps/chrome-app-developer-tool#53]
everytime I push the app to mobile it crashes. 
EDIT: I'm pushing it over the network. Ill try over usb and get back to you.

Error code: NullError: Cannot call "get$iterator" on null

**Comment by mmocny** [comment]
Sorry for the delay, xmas vacation and all..

Since I am not seeing this issue, lets start with the basics. May you give us the version of your CADT / CDE?  Have you tried using the cca command line tool to push?

**Comment by cbrez101** [comment]
My CDE version is 0.19.3489 and my CADT version is 0.11.1. No I haven't tried to use the caa command line tool to push. My error doesn't seem to be with the push I'm now realizing, when I launch on my android device(lg g3) it crashes.

**Comment by agrieve** [comment]
New version is out that uses much newer cordova-android and crosswalk. Please re-open if this still occurs.

**Comment by bitbay** [comment]
I am (occasionally) experiencing the same issue using the following setup:
* CADT v0.13.1-dev
* CED v0.20.3503 (developer preview)

with the device connected over wi-fi:
```
$adb devices
List of devices attached 
192.168.0.10:5555	device
```

Strange thing is that the first deploy worked almost flawlessly.
I wanted to try "live deploy", the things started to go bad since then, first with `SocketException: unable to connect to 127.0.0.1 2424: net::ERR_CONNECTION_REFUSED` and now this.
